#!/sbin/sh

# Remove update
rm -rf /data/app/com.samsung.groupcast*
rm -rf /system/app/AASAservice 
rm -rf /system/app/AccessControl 
rm -rf /system/app/AdvSoundDetector2015 
rm -rf /system/app/AirWakeUp 
rm -rf /system/app/ApplicationPermissions 
rm -rf /system/app/AppLinker 
rm -rf /system/app/appsearch 
rm -rf /system/app/AssistantMenu2_ZERO 
rm -rf /system/app/AutoLogin_L_M 
rm -rf /system/app/baidubrowser 
rm -rf /system/app/BasicDreams 
rm -rf /system/app/BeamService 
rm -rf /system/app/CaptivePortalLogin 
rm -rf /system/app/ChinaHolidayProvider 
rm -rf /system/app/ClockPackage_L 
rm -rf /system/app/CMAWeatherPhone2015 
rm -rf /system/app/cn.opda.a.phonoalbumshoushou 
rm -rf /system/app/DigitalClock_L 
rm -rf /system/app/DigitalClockEasy_L 
rm -rf /system/app/FactoryCamera_FB 
rm -rf /system/app/FBMessenger_stub 
rm -rf /system/app/FestivalChinaDefault 
rm -rf /system/app/FidoUafClient 
rm -rf /system/app/FilterInstaller 
rm -rf /system/app/FilterProvider 
rm -rf /system/app/GearManagerStub 
rm -rf /system/app/InteractivePanoramaViewer_WQHD 
rm -rf /system/app/Kaiti 
rm -rf /system/app/KeyguardWallpaperUpdator 
rm -rf /system/app/MediaConverter_Trim_standalone 
rm -rf /system/app/Miao 
rm -rf /system/app/minimode-res 
rm -rf /system/app/MobileTrackerEngineTwo 
rm -rf /system/app/Panorama360Viewer_Zero 
rm -rf /system/app/QuickConnect_20 
rm -rf /system/app/ResourceManager 
rm -rf /system/app/SamsungCamera4 
rm -rf /system/app/SamsungChineseIMEv9 
rm -rf /system/app/SBrowser_3.0.38 
rm -rf /system/app/SecFactoryPhoneTest 
rm -rf /system/app/ShaoNv 
rm -rf /system/app/SharingAccessibilitySettings_L 
rm -rf /system/app/ShootingModeProvider 
rm -rf /system/app/SimCardMgr 
rm -rf /system/app/SlowMotion_Zero 
rm -rf /system/app/SogouMall 
rm -rf /system/app/SPlanner_Material 
rm -rf /system/app/SPlannerWidget_Material 
rm -rf /system/app/SplitSoundService 
rm -rf /system/app/Stk 
rm -rf /system/app/Stk2 
rm -rf /system/app/UniversalSwitch 
rm -rf /system/app/Utk_Chn 
rm -rf /system/app/Utk_Chn2 
rm -rf /system/app/WeatherDaemon2015 
rm -rf /system/app/WebManual 
rm -rf /system/app/WlanTest 
rm -rf /system/app/ydzx 
rm -rf /system/app/YellowPage 

rm -rf /system/priv-app/AirMessage 
rm -rf /system/priv-app/AirMessageProxy 
rm -rf /system/priv-app/AutomationTest_FB 
rm -rf /system/priv-app/CloudAgent 
rm -rf /system/priv-app/EasyLauncher2_Zero 
rm -rf /system/priv-app/EventCenter 
rm -rf /system/priv-app/GearManager 
rm -rf /system/priv-app/GlobalNetworkLocation_Baidu 
rm -rf /system/priv-app/HealthService 
rm -rf /system/priv-app/Hearingdro_V4 
rm -rf /system/priv-app/HwModuleTest 
rm -rf /system/priv-app/OutOfFocusViewer_WQHD_K 
rm -rf /system/priv-app/PCWClientS18 
rm -rf /system/priv-app/PersonalPageService 
rm -rf /system/priv-app/PhotoStudio_WQHD_Zero 
rm -rf /system/priv-app/ProxyHandler 
rm -rf /system/priv-app/SamsungMagnifier2 
rm -rf /system/priv-app/Samsungservice2_xxxhdpi_zero 
rm -rf /system/priv-app/SAssistant_2 
rm -rf /system/priv-app/SBrowserProviderProxy_PRELOAD 
rm -rf /system/priv-app/SecCalendarProvider_NOTSTICKER 
rm -rf /system/priv-app/SecContacts_L_Phone_FLAGSHIP_CHN 
rm -rf /system/priv-app/SecContactsProvider 
rm -rf /system/priv-app/SecDownloadProvider 
rm -rf /system/priv-app/SecEmailComposer 
rm -rf /system/priv-app/SecEmailProvider 
rm -rf /system/priv-app/SecEmailSync 
rm -rf /system/priv-app/SecEmailUI 
rm -rf /system/priv-app/SecGallery2015 
rm -rf /system/priv-app/SecMms_Delight_Chn 
rm -rf /system/priv-app/SecMyFiles2015 
rm -rf /system/priv-app/SHealth4_3 
rm -rf /system/priv-app/SmartManager 
rm -rf /system/priv-app/SmartManagerSDK 
rm -rf /system/priv-app/SmartSelfShot 
rm -rf /system/priv-app/SMCore 
rm -rf /system/priv-app/SMusic 
rm -rf /system/priv-app/SPPPushClient_Prod 
rm -rf /system/priv-app/ThemeCenter 
rm -rf /system/priv-app/ThemeStore_3xh 
rm -rf /system/priv-app/VoiceWakeUp 
rm -rf /system/priv-app/ZVideo 


